name: A CD that updates the web applications and rebuilds the docker containers.
on:
  push:
    paths:
      - "app/**"
      - "poetry.lock"
      - "pyproject.toml"
    branches:
      - main

env:
  CLOUD_PROJECT_ID: "${{ vars.CLOUD_PROJECT_ID }}"
  CLOUD_APP_INSTANCE_NAME: "${{ vars.CLOUD_APP_INSTANCE_NAME }}"
  CLOUD_APP_ZONE: "${{ vars.CLOUD_APP_ZONE }}"

jobs:
  cd_update_web_app:
    name: Update Web Applications
    runs-on: ubuntu-latest

    steps:
      - name: Starting Workflow
        run: echo "Starting my first job"

      - name: Checkout the repo
        uses: actions/checkout@v4
